### Add a task
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "name": "Test Task",
  "description": "Task created from .http file"
}

### Get all tasks
GET http://localhost:3000/tasks

### Edit a task
PATCH  http://localhost:3000/tasks/1
Content-Type: application/json

{
  "name": "",
  "description": "Task modified now"
}

### Create new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "securepassword123",
  "firstname": "John",
  "lastname": "Doe"
}

### register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "fisnik@gmail.com",
  "password": "123",
  "firstname": "Jane",
  "lastname": "Doe"
}


### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "fisnik@gmail.com",
  "password": "123"
}

