### register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "fisnik@gmail.com",
  "password": "123",
  "firstname": "Jane",
  "lastname": "Doe"
}


### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "fisnik@gmail.com",
  "password": "123"
}


### Get all tasks (Requires JWT Token)
GET http://localhost:3000/tasks/
Authorization: Bearer 

### Create a new task (Requires JWT Token)
POST http://localhost:3000/tasks/
Content-Type: application/json
Authorization: Bearer 

{
  "name": "New Task",
  "description": "This is a new task.",
  "priority": "High",
  "tag": "To do"
}

### Update an existing task (Requires JWT Token)
PATCH http://localhost:3000/tasks/24
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiZmlzbmlrQGdtYWlsLmNvbSIsImlhdCI6MTczNzU4NjkzMywiZXhwIjoxNzM3NjIyOTMzfQ.3lNyZVc3leGFtqqzss2nwfZraYaLJNywboxgo1pkH9o

{
  "name": "Updated Task Name",
  "description": "Updated description for the task.",
  "priority": "Medium",
  "tag": "In Progress"
}

### Delete a task (Requires JWT Token)
DELETE http://localhost:3000/tasks/24
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiZmlzbmlrQGdtYWlsLmNvbSIsImlhdCI6MTczNzU4NjkzMywiZXhwIjoxNzM3NjIyOTMzfQ.3lNyZVc3leGFtqqzss2nwfZraYaLJNywboxgo1pkH9o


### Create new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "securepassword123",
  "firstname": "John",
  "lastname": "Doe"
}



